# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-service

SSMS:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  aliyun-access-key: LTAI5tK46ifstsHUbCryiZCg
  aliyun-access-secret: o4G6WvPQMl4k8ZTkMDp4M8tB49wsL2
