# application.yml

spring:
  profiles:
    active: dev
  application:
    name: faraday-service

server:
  error:
    whitelabel:
      enabled: false

ssms:
  common:
    sentry-dsn: https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}

